#!/usr/bin/env python
#encoding = utf-8

import re
import urllib2
from bs4 import BeautifulSoup


def regx_iteration_function(weibo_content, weibo_time):
	href = re_notext.findall(weibo_content)
	#print weibo_time + '\n'
	tweet_txt = weibo_time + '\n'

	if(len(href)):
		for i in range(len(href)):
			x0 = href[i][0]
			x1 = href[i][1]
			x2 = href[i][2]
			x3 = href[i][3]
			id_src = re_id.findall(x1)
			if(len(id_src)):
				element_url =  id_src[0][0]
				tweet_type =  id_src[0][2]
				if(tweet_type == 'former'):
					id_url = x2+'('+element_url+')'
					tweet_txt += x0+id_url+x3
				elif(tweet_type == "photo zoom"):
					img_url = 'Photo'+'('+element_url+')'
					tweet_txt += x0+img_url+x3
				elif(tweet_type == "_blank"):
					tweet_txt += x0+x2+x3
				else:
					 print 'id_src error!\n'
			else:
				tweet_txt += x0+x2+x3

	else:
		txt = re_direct.findall(weibo_content)
		if(txt):
			#print txt[0]+'\n'
			tweet_txt += txt[0]
		else:
			#print 'no more txt\n'
			tweet_txt = ' no more tweet!\n '

	return tweet_txt


def regx_function(content):

	tweet = re_tweet.findall(content)
	print "tweet length is %s\n" %len(tweet)
	print '-'*40
	weibo_content = ''
	if(len(tweet) == 0):
		print 'no tweet anymore'
		exit()
	for j in range(len(tweet)):
			tweet_tmp0 = tweet[j][0]
			tweet_tmp1 = tweet[j][1]
			weibo_content = regx_iteration_function(tweet_tmp0, tweet_tmp1)
			print weibo_content+'\n'
	print '-'*40

	return 0


if __name__ == '__main__':
	url = 'http://www.fanfou.com/'
	i=0
	page_num = 1

	while(1):
		if(i==0):
			name = raw_input("pls input the fanfou ID such as poems: ")
			print '*'*40
			if(name == "q" or name == 'Q'):
				exit()
			# page_url = 'http://www.fanfou.com/%s\n' % name
			page_url = url + name
			i=i+1
		else:
			page_name = raw_input('pls input the page number: ')
			if(page_name == 'q' or page_name == 'Q'):
				exit()
			elif(page_name == r'' or page_name == r'c'):
				page_num = page_num + 1
			elif(int(page_name)):
				page_num = int(page_name)
			else:
				print'input error'
				exit()
			# page_url = 'http://www.fanfou.com/'+name+'/p.'+str(page_num)
			page_url = url + name +'/p.'+str(page_num)
		print page_url

		xcontent = urllib2.urlopen(page_url).read()

		re_tweet = re.compile(r'<span class=\"content\">(.*?)stamp.*?class="time" title="(.*?)"')
		re_direct = re.compile(r'(.*?)</span>')
		# re_notext = re.compile(r'(.*?)<a href="(.*?)".*?(class|target)="(.*?)".*?>(.*?)</a>(.*?)(?=<)')
		re_notext = re.compile(r'(.*?)<a([^>]*?)>(.*?)</a>(.*?)(?=<)')
		# re_img = re.compile(r'(?<=src=)"+(.*?)"+.*?/')
		re_id = re.compile(r'.*?href="(.*?)".*?(class=|target=)"(.*?)"')

		fanfou_content = ''
		fanfou_content = regx_function(xcontent)

